version: '3'

services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://sit722_week7_user:9mZprc6fr3RMArAwmxh6TyHbTi18AXA3@dpg-crv4br08fa8c73cqtldg-a.oregon-postgres.render.com/sit722_week7

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722_week7_user:9mZprc6fr3RMArAwmxh6TyHbTi18AXA3@dpg-crv4br08fa8c73cqtldg-a.oregon-postgres.render.com/sit722_week7